import * as React from 'react';


import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { api } from "~/utils/api";
import  Login  from "./login/Login";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  console.log('Esto es el hello >>> ', hello)
  return (
    <>
      <Head>
        <title>SASPAV</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#e6edf2] to-[#84bbe3]">
          <div className="flex flex-col items-center">
            <Login/>
          </div>
      </main>
    </>
  );
}


