import React from 'react';
import SerdResetEmail from './components/serdResetEmail'
import Head from "next/head";

export default function ResetPassword() {
    return (
      <>
      <Head>
        <title>SASPAV</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#e6edf2] to-[#84bbe3]">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <div className="flex flex-col items-center gap-2">
              <SerdResetEmail/>
            </div>
          </div>
        </main>
      </>
    );
  }