@startuml "DTE Turno"

state Asignable {
  state Nuevo
  state Generado
  state Reprogramado
}

state NoAsignable {
  state Asignado
  state BajaCaso
  state BajaProfesional
  state ProfesionalDesasignado
}

state Atendido
state ProfesionalNoAsistió
state CasoNoAtendido

[*] --> Nuevo
[*] --> Generado
Asignable --> NoAsignable
Asignado --> Reprogramado

Asignado --> BajaCaso
Asignado --> BajaProfesional
Asignado --> ProfesionalDesasignado
Asignado --> Atendido
Asignado --> ProfesionalNoAsistió
Asignado --> CasoNoAtendido

BajaCaso --> [*]
BajaProfesional --> [*]
ProfesionalDesasignado --> [*]
Atendido --> [*]
ProfesionalNoAsistió --> [*]
CasoNoAtendido --> [*]

@enduml
