@startuml CasosUso

!theme vibrant
skinparam monochrome true

skinparam style strictuml
left to right direction

' -----------------
' | Actores       |
' -----------------

actor "Usuario" as usuario

actor Coordinador as coord
actor Profesional as pro
actor "Responsable Externo" as eti
actor "Administrador del sistema" as admin
actor "Reloj" as reloj
' coord --|> usuario
' pro --|> usuario
' eti --|> usuario
' admin --|> usuario
usuario <|-- coord
usuario <|-- pro
usuario <|-- eti
usuario <|-- admin

' -----------------
' | Casos de uso  |
' -----------------
rectangle SASPAV {
(Gestionar turno) as abmturno
(Alta/Baja Caso) as abcaso
(Moficar/Consultar Caso) as mccaso
(Alta/Baja Usuario) as altabajausuario
(Modificacion/Consulta Usuario) as modificacionconsulta
(ABMC Donante) as abmcdonante
(Blanquear contraseña a Usuario) as blanquearcontraseña
(Restablecer contraseña) as restablecercontraseña
(Cambiar contraseña) as cambiarcontraseña
(Gestionar contraseña de usuario) as gestionarcontraseña
(ABMC Recursos) as abmcrecursos
(ABM Tipo Recurso) as tiporecurso

pro --> abmturno
coord --> abmturno
coord --> abmcdonante
pro --> mccaso
pro --> (ABM Avance de caso)
pro --> (Gestionar horarios)
coord --> abcaso
coord --> mccaso
coord --> tiporecurso
eti --> abcaso
eti --> mccaso
coord --> (Asignar profesional a caso)
coord --> (Asignar recurso a caso)
coord --> abmcrecursos
coord --> (Generar reportes)

admin --> (ABMC Rol)
admin --> blanquearcontraseña
admin --> altabajausuario
admin --> (Establecer Rol a Usuario)
admin --> (ABMC Profesión)
admin --> (ABMC Estado de caso)
admin --> (Exportar sistema a archivo)
' admin --> (Restablecer sistema desde archivo)

usuario --> restablecercontraseña
usuario --> modificacionconsulta
usuario --> gestionarcontraseña

reloj --> (Alertar vencimiento de recursos)

' altausuario .> blanquearcontraseña: "<<include>>"
' abmcdonante .> abmcrecursos: "<<extend>>"

' remove blanquearcontraseña
' remove restablecercontraseña
' remove cambiarcontraseña

' -----------------
' | Notas         |
' -----------------

note as notaturno
El coordinador asigna el primer
turno de un caso con el profesional.
El profesional asignar los turnos
siguientes.
end note
abmturno .. notaturno

}

@enduml